global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'movie-catalog-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movie-service:8080']